{{ if and (eq .Values.postgres.type "external") (not .Values.postgres.external.secret.existingSecretName )}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-geonode-external-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  geonode-password: {{ .Values.postgres.external.secret.geonode_password | b64enc }}
{{ end }}
