apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-geonode-k8s-settings-additions-py
data:
  geonode-k8s-settings-additions.py: {{- .Values.geonode.general.settings_additions | toYaml | indent 1 }}

