{{- if empty .Values.geonode.secret.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "geonode_secret_name" . }}"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # superuser credentials
  ADMIN_USERNAME: {{ .Values.geonode.secret.superUser.username | b64enc }}
  ADMIN_PASSWORD: {{ .Values.geonode.secret.superUser.password | b64enc }}
  ADMIN_EMAIL: {{ .Values.geonode.secret.superUser.email | b64enc }}

  # mail secrets
  DJANGO_EMAIL_HOST_USER: {{ .Values.geonode.secret.mail.user | b64enc }}
  DJANGO_EMAIL_HOST_PASSWORD: {{ .Values.geonode.secret.mail.password | b64enc }}
  DEFAULT_FROM_EMAIL: {{ .Values.geonode.secret.mail.from | b64enc }}

  # ldap secrets
  LDAP_BIND_PASSWORD: {{ .Values.geonode.secret.ldap.bind_password | b64enc }}

  # OAuth2
  OAUTH2_API_KEY: ""
  OAUTH2_CLIENT_ID: {{ .Values.geonode.secret.oauth2.clientId | b64enc }}
  OAUTH2_CLIENT_SECRET: {{ .Values.geonode.secret.oauth2.clientSecret | b64enc }}
{{ end }}