global:
  storageClass: standard

geonode:
  replicaCount: 1 # not working yet

  general:
    debug: True
    debug_static: True
    externalScheme: http
    externalDomain: geonode

  persistant:
    storageSize: 2Gi

  ingress:
    enabled: False

  secret:
    superUser:
      password: geonode

  mail:
    enabled: False

  ldap:
    enabled: False

  register:
    open_signup: True
    email_verification: "False"
    authentication_method: username_email

rabbitmq:
  replicaCount: 1
  auth:
    username: rabbituser
    password: rabbit_password

postgres:
  type: external
  username: postgres
  geonode_databasename_and_username: geonode
  geodata_databasename_and_username: geodata

  external:
    hostname: geonode-postgresql
    port: 5432
    secret:
      postgres_password: mJVulBcn8ivuAW5LdUeZGyDVumKqSA4otCfqntTm1a8nv8sXbFmEf8oUSyX7JUHq
      geonode_password: frNyGcl68Cr93BCWiafXNwW37fiB191q3W1ty9aRbuXGQfFakxoLjNjktROz75MY
      geodata_password: MbTQLeoySfxKW4tCDDmz07xSDb5V8I50nJ2KXguXqTDsBbvVgy0b61xQXWbliUJA

postgres-operator:
  enabled: False
