
kind: Service
apiVersion: v1
metadata:
  name: "{{ include "geoserver_pod_name" . }}"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    org.geonode.instance: "{{ include "geoserver_pod_name" . }}"
  ports:
  - targetPort: {{ .Values.geoserver.port }}
    port: {{ .Values.geoserver.port }}
    name: http
  type: ClusterIP