{{- if empty .Values.geoserver.secret.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "geoserver_secret_name" . }}"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # geoserver admin credentials
  GEOSERVER_ADMIN_USER: {{ .Values.geoserver.secret.admin_username | b64enc }}
  GEOSERVER_ADMIN_PASSWORD: {{ .Values.geoserver.secret.admin_password | b64enc }}
  GEOSERVER_FACTORY_PASSWORD: {{ .Values.geoserver.secret.admin_factory_password | b64enc }}
  # geonode oauth2
  OAUTH2_API_KEY: ""
  OAUTH2_CLIENT_ID: {{ .Values.geonode.secret.oauth2.clientId | b64enc}}
  OAUTH2_CLIENT_SECRET: {{ .Values.geonode.secret.oauth2.clientSecret | b64enc }}
  {{- with .Values.geoserver.secret.extraSecrets }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
{{ end }}