apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geoserver_pod_name" . }}-env
  namespace: {{ .Release.Namespace }}
data:
  GEONODE_LB_HOST_IP: {{ .Values.geonode.general.externalDomain | quote }}
  SUBSTITUTION_URL: "{{ include "public_url" . }}"
  GEONODE_HOST_IP: localhost

  DJANGO_URL: http://{{ include "geonode_pod_name" .}}/
  ENABLE_JSONP: 'true'
  outFormat: text/javascript
  # trimSuffix trims of suffix "i" coming from resources memory in Gi or Mi
  GEOSERVER_JAVA_OPTS: "-Xms{{ .Values.geoserver.resources.requests.memory | trimSuffix "i" }} -Xmx{{ .Values.geoserver.resources.limits.memory | trimSuffix "i" }} -Djava.awt.headless=true -Dgwc.context.suffix=gwc -XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/log/jvm.log -XX:PerfDataSamplingInterval=500 -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=false -DGS-SHAPEFILE-CHARSET=UTF-8 -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL={{ include "public_url" . }}/geoserver/pdf -DALLOW_ENV_PARAMETRIZATION=true -Xbootclasspath/a:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin-0.9.3-Unsafe.jar -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine"
  NGINX_BASE_URL: "{{ include "public_url" . }}"

  DATABASE_HOST: "{{ include "database_hostname" . }}"
  DATABASE_PORT: "{{ include "database_port" . }}"
  GEONODE_GEODATABASE: {{ .Values.postgres.geodata_databasename_and_username | quote  }}
  GEONODE_GEODATABASE_SCHEMA: {{ .Values.postgres.schema | quote }}
  FORCE_REINIT: {{ .Values.geoserver.force_reinit | quote }}

  {{- with .Values.geoserver.extraConfigMap }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
